# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('tag_type', models.CharField(default='', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tag', to='backend.Client')),
            ],
        ),
        migrations.RemoveField(
            model_name='tags',
            name='client',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
