# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160410_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='client',
        ),
        migrations.AddField(
            model_name='tag',
            name='client',
            field=models.ManyToManyField(related_name='client_tag', to='backend.Client'),
        ),
    ]
