# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_item_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='comp_interaction',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='src_interaction',
        ),
    ]
