# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20160417_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='route',
        ),
    ]
