# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-24 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20160417_1903'),
        ('backend', '0003_auto_20160410_1551'),
    ]

    operations = [
    ]
