# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-24 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='story',
            field=models.CharField(default='', max_length=300),
        ),
    ]
