# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_client_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
