# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_interaction_title'),
        ('backend', '0009_interaction_title'),
    ]

    operations = [
    ]
