# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='amount',
        ),
    ]
