# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-30 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_requests_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='backend.Item'),
        ),
    ]
